[phases.setup]
nixPkgs = ["python3", "gcc", "glibc", "nodejs"]

[phases.install]
cmds = ["npm install --legacy-peer-deps", "npm install --platform=linux --arch=arm64 sharp"]

[build]
cmds = ["npm run build"]

[start]
cmds = ["npm run start"]