[phases.install]
  cmds = [
    'apt update && apt install -y python3',
    'npm config set python /usr/bin/python3',
    'apt install -y build-essential python3',
    'npm install']

[build]
  cmd = 'npm run build'

[start]
  cmd = 'npm run start'