[phases.setup]
nixPkgs = ["python3", "gcc", "glibc", "nodejs"]

[phases.install]
cmds = ["npm install --legacy-peer-deps", "npm install --cpu=x64 --os=linux sharp"]

[build]
cmds = ["npm run build"]

[start]
cmds = ["npm run start"]