[phases.setup]
nixPkgs = ["python3", "gcc", "glibc", "nodejs"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["npm run start"]