[phases.setup]
nixPkgs = ["python3", "gcc", "glibc", "nodejs"]

[phases.install]
cmds = [
    "npm install --legacy-peer-deps", 
    "npm install --platform=linux --arch=arm64 sharp",
    "npm install --platform=linux --arch=arm64 @tensorflow/tfjs-node"
    ]

[build]
cmds = ["npm run build"]

[start]
cmds = ["npm run start"]